---
title: "examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(gmrc.bayes)
library(ggdist)
```


# norm_B

```{r}
oneMeanEstim(rnorm(97,10,15),alpha = 0.15,mu_0 = 0 ,kappa_0 = 1,alpha_0 = 0.005,beta_0 = 0.01,seuil = 10,theta_P = c(-10,5),theta_A = c(5,12)) 
```

```{r}
res<-oneMeanEstim(rnorm(97,10,15),alpha = 0.15,mu_0 = 0 ,kappa_0 = 1,alpha_0 = 0.005,beta_0 = 0.01,seuil = 10,theta_P = c(-10,5),theta_A = c(5,12)) 
res$twit

plotOneMeanEstim(oneMeanEstimRes = res)

```

```{r}
plot(res)

res<-oneMeanEstim(rnorm(97,10,15),alpha = 0.15,mu_0 = 0 ,kappa_0 = 1,alpha_0 = 0.005,beta_0 = 0.01,seuil = 10) 
res$twit

plotOneMeanEstim(oneMeanEstimRes = oneMeanEstim(rnorm(97,10,15),alpha = 0.15,mu_0 = 0 ,kappa_0 = 1,alpha_0 = 0.005,beta_0 = 0.01,seuil = 10) ,twit=F)
```
```{r}
ifelse_perso <- function(log, x, y ){
  if(log) return(x)
  return(y)
}
```

